const LABEL = {
    LOGIN_TITLE: 'Bem vindo',
    EMAIL: 'E-mail',
    PASSWORD: 'Senha',
    LOGIN: 'Entrar',
    PASSWORD_RESET: 'Não lembro minha senha',
    EMAIL_FORGOT: 'Esqueci meu email',
    HIRE_HERE_TEXT : 'Ainda não é BMG?',
    HIRE_HERE:'Contrate aqui',
    RECOVER_ACCESS: 'Recuperar acesso',
    MY_SUBSCRIPTIONS: 'Minhas assinaturas',
    MY_DATA: 'Meus dados',
    ACTIVATE_SINISTER: 'Acionar sinistro',
    SAC: 'SAC',
    CPF: 'CPF',
    NAME: 'Nome',
    BIRTH_DATE: 'Data de Nascimento',
    GENRE: 'Gênero',
    PHONE: 'Celular',
    EDIT: 'Editar',
    SAVE: 'Salvar',
    CANCEL: 'Cancelar',
    COVERAGE: 'Cobertura',
    CHANGE_LIMIT: 'Alterar Limite',
    COVERAGE_LIMIT: 'Limite de cobertura de até',
    COVERAGE_LABEL_01: 'Roubo e Furto: até',
    COVERAGE_LABEL_02: 'Danos Elétricos: até',
    CONFIRM_CHANGE: 'Confirmar alteração',
    CANCEL_PLAN: 'Cancelar plano',
    PLAN_CERTIFICATE: 'Certificado do plano',
    SERVICE_MANUAL: 'Manual das assistências',
    GENERAL_COVERAGE_CONDITIONS: 'Condições gerais das coberturas',
    DOCUMENTS: 'Documentos',
    ABOUT_THE_PLAN: 'Sobre o plano',
    ADDRESS: 'Endereço',
    CHANGE_ADDRESS: 'Alterar Endereço',
    EDIT_MY_ADDRESS: 'Edite o seu endereço de cobertura',
    CURRENT_ADDRESS: 'Endereço atual',
    CEP: 'CEP',
    STREET: 'Rua',
    NUMBER: 'Número',
    COMPLEMENT: 'Complemento',
    CITY: 'Cidade',
    STATE: 'Estado',
    NEIGHBORHOOD: 'Bairro',
    SAVE_NEW_ADDRESS: 'Salvar novo endereço',
    EXIT: 'Sair'



}

export default LABEL